name: Java Application Build

defaults:
  run:
    working-directory: ./app_java

on:
  workflow_dispatch:
  pull_request:
    paths:
      - ./app_java/src/**
      - src/**

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build
    permissions:
      packages: write
      pull-requests: write

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: maven build
        run: mvn package
